name: 'Action Check Typescript errors'
description: 'Check tsc errors and compare errors wih base branch'
author: 'Arhia'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  directory:
    description: "Directory where to run install and build. Default is '.'"
    default: '.'
  files-changed:
    description: "List of files changed in the current PR (separated by space), use action 'futuratrepadeira/changed-files' for that"
    default: ''
  config-path:
    description: "Path of json file for linters configuration. default is '.'"
    default: '.github/linters_config.json'
  use-check:
    description: 'Report status as a CI Check'
runs:
  using: 'node12'
  main: 'dist/index.js'
